/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppVaccinationsRouteImport } from './routes/app/vaccinations'
import { Route as AppTimelineRouteImport } from './routes/app/timeline'
import { Route as AppRecordsRouteImport } from './routes/app/records'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPetsRouteImport } from './routes/app/pets'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as DashboardSupportIndexRouteImport } from './routes/dashboard/support/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVaccinationsRoute = AppVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPetsRoute = AppPetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const DashboardSupportIndexRoute = DashboardSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/vaccinations': typeof AppVaccinationsRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/vaccinations': typeof AppVaccinationsRoute
  '/app': typeof AppIndexRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/support': typeof DashboardSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/pets': typeof AppPetsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/records': typeof AppRecordsRoute
  '/app/timeline': typeof AppTimelineRoute
  '/app/vaccinations': typeof AppVaccinationsRoute
  '/app/': typeof AppIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/chat'
    | '/app/pets'
    | '/app/profile'
    | '/app/records'
    | '/app/timeline'
    | '/app/vaccinations'
    | '/app/'
    | '/auth/'
    | '/dashboard/profile/'
    | '/dashboard/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/app/chat'
    | '/app/pets'
    | '/app/profile'
    | '/app/records'
    | '/app/timeline'
    | '/app/vaccinations'
    | '/app'
    | '/auth'
    | '/dashboard/profile'
    | '/dashboard/support'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/dashboard'
    | '/login'
    | '/app/chat'
    | '/app/pets'
    | '/app/profile'
    | '/app/records'
    | '/app/timeline'
    | '/app/vaccinations'
    | '/app/'
    | '/auth/'
    | '/dashboard/profile/'
    | '/dashboard/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vaccinations': {
      id: '/app/vaccinations'
      path: '/vaccinations'
      fullPath: '/app/vaccinations'
      preLoaderRoute: typeof AppVaccinationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/timeline': {
      id: '/app/timeline'
      path: '/timeline'
      fullPath: '/app/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pets': {
      id: '/app/pets'
      path: '/pets'
      fullPath: '/app/pets'
      preLoaderRoute: typeof AppPetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/dashboard/support/': {
      id: '/dashboard/support/'
      path: '/support'
      fullPath: '/dashboard/support/'
      preLoaderRoute: typeof DashboardSupportIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppPetsRoute: typeof AppPetsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppVaccinationsRoute: typeof AppVaccinationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppPetsRoute: AppPetsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppVaccinationsRoute: AppVaccinationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface DashboardRouteChildren {
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSupportIndexRoute: typeof DashboardSupportIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSupportIndexRoute: DashboardSupportIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
