/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as DashboardVaccinationsRouteImport } from './routes/dashboard/vaccinations'
import { Route as DashboardTimelineRouteImport } from './routes/dashboard/timeline'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard/records'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardSupportIndexRouteImport } from './routes/dashboard/support/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardPetsIndexRouteImport } from './routes/dashboard/pets/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVaccinationsRoute = DashboardVaccinationsRouteImport.update({
  id: '/vaccinations',
  path: '/vaccinations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTimelineRoute = DashboardTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSupportIndexRoute = DashboardSupportIndexRouteImport.update({
  id: '/support/',
  path: '/support/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPetsIndexRoute = DashboardPetsIndexRouteImport.update({
  id: '/pets/',
  path: '/pets/',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/vaccinations': typeof DashboardVaccinationsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pets/': typeof DashboardPetsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/vaccinations': typeof DashboardVaccinationsRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/pets': typeof DashboardPetsIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/support': typeof DashboardSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/dashboard/timeline': typeof DashboardTimelineRoute
  '/dashboard/vaccinations': typeof DashboardVaccinationsRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/pets/': typeof DashboardPetsIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/support/': typeof DashboardSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/chat'
    | '/dashboard/records'
    | '/dashboard/timeline'
    | '/dashboard/vaccinations'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/pets/'
    | '/dashboard/profile/'
    | '/dashboard/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/chat'
    | '/dashboard/records'
    | '/dashboard/timeline'
    | '/dashboard/vaccinations'
    | '/auth'
    | '/dashboard'
    | '/dashboard/pets'
    | '/dashboard/profile'
    | '/dashboard/support'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/chat'
    | '/dashboard/records'
    | '/dashboard/timeline'
    | '/dashboard/vaccinations'
    | '/auth/'
    | '/dashboard/'
    | '/dashboard/pets/'
    | '/dashboard/profile/'
    | '/dashboard/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vaccinations': {
      id: '/dashboard/vaccinations'
      path: '/vaccinations'
      fullPath: '/dashboard/vaccinations'
      preLoaderRoute: typeof DashboardVaccinationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/timeline': {
      id: '/dashboard/timeline'
      path: '/timeline'
      fullPath: '/dashboard/timeline'
      preLoaderRoute: typeof DashboardTimelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/support/': {
      id: '/dashboard/support/'
      path: '/support'
      fullPath: '/dashboard/support/'
      preLoaderRoute: typeof DashboardSupportIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pets/': {
      id: '/dashboard/pets/'
      path: '/pets'
      fullPath: '/dashboard/pets/'
      preLoaderRoute: typeof DashboardPetsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  DashboardTimelineRoute: typeof DashboardTimelineRoute
  DashboardVaccinationsRoute: typeof DashboardVaccinationsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPetsIndexRoute: typeof DashboardPetsIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardSupportIndexRoute: typeof DashboardSupportIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardChatRoute: DashboardChatRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  DashboardTimelineRoute: DashboardTimelineRoute,
  DashboardVaccinationsRoute: DashboardVaccinationsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPetsIndexRoute: DashboardPetsIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardSupportIndexRoute: DashboardSupportIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthIndexRoute: AuthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
